name: Lint and Format Code

on:
  pull_request:
    branches: [ main ]
  
jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black
        
    - name: Run linter
      run: flake8 .
      
    - name: Check code formatting
      run: black . --check
